Add aarch64 wheel build support
OpenNMT/Tokenizer pull request #272
Opened 2021-11-17 11:09 UTC by odidev

Added linux aarch64 wheel support.

2021-11-17 12:08 UTC, odidev commented
@guillaumekln 
Yes, I have checked the same, In GitHub Actions the build for AArch64 took an hour and 15 minutes on average.
please check this link for more details: https://github.com/odidev/Tokenizer/actions/runs/1471078391

2021-11-19 13:36 UTC, guillaumekln requested changes

2021-11-19 13:36 UTC, guillaumekln commented on .github/workflows/ci.yml
> +        arch: [auto]
```suggestion
        arch: [auto64]
```

2021-11-19 13:36 UTC, guillaumekln commented on .github/workflows/ci.yml
> +          CIBW_ARCHS_LINUX: ${{matrix.arch}}
```suggestion
          CIBW_ARCHS: ${{matrix.arch}}
```

2021-11-19 13:36 UTC, guillaumekln commented on .github/workflows/ci.yml
> +    name: Build and test wheels on ${{matrix.arch}} for ${{ matrix.os }}
I think the other way around is more correct?

```suggestion
    name: Build and test wheels on ${{ matrix.os }} for ${{matrix.arch}} 
```

2021-11-25 11:37 UTC, guillaumekln approved these changes

2021-11-26 08:54 UTC, merged